// The Carpathian Crescent — Nation Definitions
// Ported from sim/data/nations.json

export const WORLD = {
  name: "Carpathian Crescent",
  description: "A fictional Eastern European peninsula of five nations.",
  eraStartYear: 1918,
  eraEndYear: 2025,
};

export const NATIONS = {
  moravia_nord: {
    name: "Moravia-Nord",
    capital: "Nordhaven",
    population1918M: 2.8,
    areaKm2: 42000,
    geography: {
      coastal: true,
      landlocked: false,
      terrain: "flat_coastal",
      naturalResources: ["fish", "timber", "moderate_coal"],
      portAccess: true,
      riverNetwork: "moderate",
      description: "Small coastal nation with natural harbors and flat terrain."
    },
    ethnicFragmentation: 0.31,
    era1Start: {
      gdpPerCapitaPPP: 2100,
      giniCoefficient: 0.48,
      literacyRate: 0.72,
      lifeExpectancy: 54,
      urbanizationRate: 0.28,
      agriculturalLaborShare: 0.62,
      industrialLaborShare: 0.18,
      institutionalLegacy: "austro_hungarian",
      institutionalQuality: 0.45,
      institutionalDepth: 40,
      infrastructureQuality: 0.38,
      railKm: 420,
      pavedRoadKm: 180,
      electricityAccessPct: 0.12,
      dCoefficient: 38,
    },
    legacyDescription: "Austro-Hungarian administrative tradition provides strong institutional foundations."
  },
  zaleskia: {
    name: "Zaleskia",
    capital: "Zalesk",
    population1918M: 8.2,
    areaKm2: 128000,
    geography: {
      coastal: false,
      landlocked: true,
      terrain: "river_plains_uplands",
      naturalResources: ["coal_abundant", "iron_ore", "timber", "limestone"],
      portAccess: false,
      riverNetwork: "extensive",
      description: "Large landlocked nation with abundant coal and iron."
    },
    ethnicFragmentation: 0.67,
    era1Start: {
      gdpPerCapitaPPP: 1800,
      giniCoefficient: 0.55,
      literacyRate: 0.55,
      lifeExpectancy: 48,
      urbanizationRate: 0.22,
      agriculturalLaborShare: 0.68,
      industrialLaborShare: 0.22,
      institutionalLegacy: "mixed_imperial",
      institutionalQuality: 0.32,
      institutionalDepth: 25,
      infrastructureQuality: 0.30,
      railKm: 890,
      pavedRoadKm: 310,
      electricityAccessPct: 0.08,
      dCoefficient: 26,
    },
    legacyDescription: "A patchwork of former imperial territories stitched together."
  },
  livonia_podolia: {
    name: "Livonia-Podolia",
    capital: "Livonsk",
    population1918M: 5.1,
    areaKm2: 94000,
    geography: {
      coastal: false,
      landlocked: true,
      terrain: "fertile_plains",
      naturalResources: ["agricultural_land_excellent", "limited_lignite"],
      portAccess: false,
      riverNetwork: "moderate",
      description: "Vast fertile plains — the breadbasket of the Crescent."
    },
    ethnicFragmentation: 0.48,
    era1Start: {
      gdpPerCapitaPPP: 1400,
      giniCoefficient: 0.62,
      literacyRate: 0.38,
      lifeExpectancy: 45,
      urbanizationRate: 0.14,
      agriculturalLaborShare: 0.78,
      industrialLaborShare: 0.08,
      institutionalLegacy: "ottoman",
      institutionalQuality: 0.18,
      institutionalDepth: 12,
      infrastructureQuality: 0.15,
      railKm: 210,
      pavedRoadKm: 80,
      electricityAccessPct: 0.02,
      dCoefficient: 14,
    },
    legacyDescription: "Ottoman-era landowner institutions dominate."
  },
  vynahrad_republic: {
    name: "Vynahrad Republic",
    capital: "Vynagrad",
    population1918M: 3.4,
    areaKm2: 62000,
    geography: {
      coastal: false,
      landlocked: true,
      terrain: "mountainous",
      naturalResources: ["oil_major", "natural_gas", "minerals_diverse", "timber"],
      portAccess: false,
      riverNetwork: "limited",
      description: "Mountainous nation sitting on major oil and gas reserves."
    },
    ethnicFragmentation: 0.61,
    era1Start: {
      gdpPerCapitaPPP: 1600,
      giniCoefficient: 0.58,
      literacyRate: 0.42,
      lifeExpectancy: 46,
      urbanizationRate: 0.16,
      agriculturalLaborShare: 0.65,
      industrialLaborShare: 0.12,
      institutionalLegacy: "extractive_colonial",
      institutionalQuality: 0.15,
      institutionalDepth: 8,
      infrastructureQuality: 0.18,
      railKm: 140,
      pavedRoadKm: 45,
      electricityAccessPct: 0.04,
      dCoefficient: 12,
    },
    legacyDescription: "Resource wealth with extractive institutions — the classic resource curse setup."
  },
  karpathia: {
    name: "Karpathia",
    capital: "Karpagrad",
    population1918M: 1.6,
    areaKm2: 28000,
    geography: {
      coastal: false,
      landlocked: true,
      terrain: "alpine",
      naturalResources: ["timber", "hydropower_potential", "tourism_natural"],
      portAccess: false,
      riverNetwork: "limited",
      description: "Small alpine nation in strategic mountain passes."
    },
    ethnicFragmentation: 0.65,
    era1Start: {
      gdpPerCapitaPPP: 1900,
      giniCoefficient: 0.42,
      literacyRate: 0.68,
      lifeExpectancy: 52,
      urbanizationRate: 0.20,
      agriculturalLaborShare: 0.55,
      industrialLaborShare: 0.15,
      institutionalLegacy: "alpine_communal",
      institutionalQuality: 0.38,
      institutionalDepth: 30,
      infrastructureQuality: 0.22,
      railKm: 180,
      pavedRoadKm: 95,
      electricityAccessPct: 0.10,
      dCoefficient: 22,
    },
    legacyDescription: "Alpine communal traditions create surprisingly strong local institutions."
  },
};
